#!/bin/bash
#examples for grabbing prices from exchange orderbooks and setting them into a redis entry called Exchange_Rates
FUEL2BTC=`curl -G 'http://pubapi.cryptsy.com/api.php?method=singlemarketdata&marketid=460' | jq -r .return.markets.FC2.buyorders[3].price`
NEOS2BTC=`curl -G 'https://bittrex.com/api/v1.1/public/getorderbook?market=BTC-NEOS&type=both&depth=5' | jq -r .result.buy[4].Rate|awk {' printf "%.8f",$1 '}`

redis-cli hset Exchange_Rates fuelcoin $FUEL2BTC
redis-cli hset Exchange_Rates neoscoin $NEOS2BTC
